server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: reader
    password: 123456
    servlet:
      multipart:
        enabled: true #开 启文件上传
        max-file-size: 10MB # 限制文件上传大小为10M
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    redis:
      host: 192.168.200.130 # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口




# 自定义
jwt:
  tokenHeader: Authorization # JWT存储的请求头
  secret: mySecret # JWT加解密使用的密钥
  expiration: 604800 # JWT的超期限时间(60*60*24)
  tokenHead: Bearer # JWT负载中拿到头

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

springdoc:
  swagger-ui:
    # 修改Swagger UI路径
    path: /swagger-ui.html
    # 开启Swagger UI界面
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'mall-admin'
      paths-to-match:
        - '/brand/**'
        - '/minio/**'
        - '/admin/**'
      packages-to-scan: com.oypj.mall.controller
    - group: 'mall-portal'
      paths-to-match:
        - '/order/**'
        - '/sso/**'
        - '/member/**'
      packages-to-scan: com.oypj.mall.controller
    - group: 'mall-search'
      paths-to-match:
        - '/esProduct/**'
      packages-to-scan: com.oypj.mall.controller
  default-flat-param-object: false